<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Wojtryb Krita Scripts</text>

        <Action name="Backup Layer">
        <icon>duplicatelayer</icon>
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Remove Hidden Layers">
        <icon>deletelayer</icon>
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
</ActionCollection>
